/// Flutter icons QepiIcons
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QepiIcons
///      fonts:
///       - asset: fonts/QepiIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class QepiIcons {
  QepiIcons._();

  static const _kFontFam = 'QepiIcons';

  static const IconData kilo__3_ = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData event = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData travel__1_ = const IconData(0xe802, fontFamily: _kFontFam);
  static const IconData shopping_bag = const IconData(0xe803, fontFamily: _kFontFam);
  static const IconData medical_notes_symbol_of_a_list_paper_on_a_clipboard = const IconData(0xe804, fontFamily: _kFontFam);
  static const IconData open_box = const IconData(0xe805, fontFamily: _kFontFam);
  static const IconData money = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData box = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData luggage = const IconData(0xe808, fontFamily: _kFontFam);
  static const IconData time = const IconData(0xe809, fontFamily: _kFontFam);
  static const IconData travel__2_ = const IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData edit = const IconData(0xe80b, fontFamily: _kFontFam);
}
