/// Flutter icons QepiIconsItemTypes
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  QepiIconsItemTypes
///      fonts:
///       - asset: fonts/QepiIconsItemTypes.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class QepiIconsItemTypes {
  QepiIconsItemTypes._();

  static const _kFontFam = 'QepiIconsItemTypes';

  static const IconData earrings = const IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData souvenir = const IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData smartphone = const IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData goalkeeper = const IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData sweater = const IconData(0xe810, fontFamily: _kFontFam);
  static const IconData donation = const IconData(0xe811, fontFamily: _kFontFam);
  static const IconData jeans = const IconData(0xe812, fontFamily: _kFontFam);
  static const IconData shoe = const IconData(0xe813, fontFamily: _kFontFam);
}
